Repository ITU-BDSA2024-GROUP1/Chirp, pull requests merged in 2024-11, with the labels that each got.

#66 Slight refactoring
  data/chirp.db
  src/Chirp.Core/Data/ChirpDBContext.cs
  src/Chirp.Core/Data/ChirpDBContextFactory.cs
  src/Chirp.Core/DataTransferObject/AuthorDTO.cs
  src/Chirp.Core/DataTransferObject/CheepDTO.cs
  src/Chirp.Core/DbInitializer.cs
  src/Chirp.Core/Entities/Author.cs
  src/Chirp.Core/Entities/Cheep.cs
  src/Chirp.Core/Migrations/20241106103427_InitialDBSchema.Designer.cs
  src/Chirp.Core/Migrations/20241106103427_InitialDBSchema.cs
  src/Chirp.Core/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Core/Repositories/AuthorRepository.cs
  src/Chirp.Core/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/AuthorService/AuthorService.cs
  src/Chirp.Infrastructure/CheepService/CheepService.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/Register.cshtml.cs
  src/Chirp.Razor/Chirp.Razor.csproj
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Razor/TestEnvironmentManager.cs
  src/Chirp.Razor/appsettings.json
  test/Chirp.CoreTest/CheepRepositoryUnitTest.cs
  test/Chirp.CoreTest/CoreRepositoryTester.cs
  test/Chirp.InfrastructureTest/InfrastructureServiceTester.cs
  test/Chirp.RazorTest/IntegrationTest.cs
Labels: refactoring

#62 #54 added javascript to make the optional part of issue 54, characters left counter, work
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/wwwroot/css/style.css
Labels: enhancement

#67 Authentication GitHub
  .github/workflows/build and test on requests.yml
  data/chirp.db
  src/Chirp.Core/DbInitializer.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/FinishGithubLogin.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/FinishGithubLogin.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/Logout.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/Register.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/Register.cshtml.cs
  src/Chirp.Razor/Program.cs
  test/Chirp.RazorTest/IntegrationTest.cs
Labels: bug, enhancement, refactoring

#73 #68 Only allowed to use username and password for login
  src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml.cs
Labels: refactoring

#74 #69 GitHub fix
  data/chirp.db
  src/Chirp.Core/DbInitializer.cs
  src/Chirp.Core/Entities/Author.cs
  src/Chirp.Core/Migrations/20241119075821_InitialDBSchema.Designer.cs
  src/Chirp.Core/Migrations/20241119075821_InitialDBSchema.cs
  src/Chirp.Core/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Core/Repositories/CheepRepository.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/ExistingUsername.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/ExistingUsername.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Chirp.Razor/Areas/Identity/Pages/Account/FinishGithubLogin.cshtml
  src/Chirp.Razor/Areas/Identity/Pages/Account/FinishGithubLogin.cshtml.cs
Labels: bug, refactoring
