Repository ITU-BDSA2024-GROUP1/Chirp, pull requests merged in 2024-10, with the labels that each got.

#42 #32 Pagination
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
Labels: enhancement, refactoring

#48 Razorpage week40
  Chirp.sln
  data/chirp.db
  data/chirp_cli_db.csv
  data/test.csv
  src/Chirp.Core/Cheep.cs
  src/Chirp.Core/Chirp.Core.csproj
  src/Chirp.Core/Data/ChirpDBContext.cs
  src/Chirp.Core/Data/ChirpDBContextFactory.cs
  src/Chirp.Core/DataTransferObject/AuthorDTO.cs
  src/Chirp.Core/DataTransferObject/CheepDTO.cs
  src/Chirp.Core/DbInitializer.cs
  src/Chirp.Core/Entities/Author.cs
  src/Chirp.Core/Entities/Cheep.cs
  src/Chirp.Core/Migrations/20241008134359_InitialDBSchema.Designer.cs
  src/Chirp.Core/Migrations/20241008134359_InitialDBSchema.cs
  src/Chirp.Core/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Core/Models/PagedResult.cs
  src/Chirp.Core/Repositories/AuthorRepository.cs
  src/Chirp.Core/Repositories/CheepRepository.cs
  src/Chirp.Core/Repositories/IAuthorRepository.cs
  src/Chirp.Core/Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/CheepService.cs
  src/Chirp.Infrastructure/Chirp.Infrastructure.csproj
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Chirp.Razor.csproj
  src/Chirp.Razor/DBFacade.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Razor/appsettings.json
Labels: enhancement, refactoring

#58 #39 CoreUnitTestsAndBugFixes
  src/Chirp.Core/DirectoryFixer.cs
  src/Chirp.Core/Repositories/CheepRepository.cs
  test/Chirp.CoreTest/CoreUnitTest.cs
Labels: enhancement, Testing

#59 ImprovedTestsAndGeneralRefactoring
  src/Chirp.Core/DataTransferObject/AuthorDTO.cs
  src/Chirp.Core/DataTransferObject/CheepDTO.cs
  src/Chirp.Core/DbInitializer.cs
  src/Chirp.Core/Entities/Author.cs
  src/Chirp.Core/Models/PagedResult.cs
  src/Chirp.Core/Repositories/AuthorRepository.cs
  src/Chirp.Core/Repositories/CheepRepository.cs
  src/Chirp.Core/Repositories/IAuthorRepository.cs
  src/Chirp.Core/Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/AuthorService.cs
  src/Chirp.Infrastructure/AuthorService/AuthorService.cs
  src/Chirp.Infrastructure/AuthorService/AuthorViewModel.cs
  src/Chirp.Infrastructure/AuthorService/IAuthorService.cs
  src/Chirp.Infrastructure/CheepService/CheepService.cs
  src/Chirp.Infrastructure/CheepService/CheepViewModel.cs
  src/Chirp.Infrastructure/CheepService/ICheepService.cs
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/Program.cs
  test/Chirp.CoreTest/AssemblyInfo.cs
  test/Chirp.CoreTest/AuthorRepositoryUnitTest.cs
  test/Chirp.CoreTest/CheepRepositoryUnitTest.cs
  test/Chirp.CoreTest/CoreRepositoryTester.cs
  test/Chirp.CoreTest/CoreUnitTest.cs
  test/Chirp.CoreTest/UnitTestCore.cs
  test/Chirp.InfrastructureTest/AuthorServiceUnitTest.cs
  test/Chirp.InfrastructureTest/CheepServiceUnitTest.cs
  test/Chirp.InfrastructureTest/InfrastructureServiceTester.cs
  test/Chirp.RazorTest/EndToEndTest.cs
  test/Chirp.RazorTest/IntegrationTest.cs
Labels: refactoring
