Repository ITU-BDSA2024-GROUP1/Chirp, pull requests merged in 2024-12, with the labels that each got.

#86 Aboutme feature
  data/chirp.db
  src/Chirp.Core/Repositories/CheepRepository.cs
  src/Chirp.Core/Repositories/FollowRepository.cs
  src/Chirp.Core/Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/CheepService/CheepService.cs
  src/Chirp.Infrastructure/CheepService/ICheepService.cs
  src/Chirp.Razor/Pages/AboutMe.cshtml
  src/Chirp.Razor/Pages/AboutMe.cshtml.cs
  src/Chirp.Razor/Pages/Shared/_Layout.cshtml
  test/Chirp.CoreTest/CheepRepositoryUnitTest.cs
  test/Chirp.InfrastructureTest/CheepServiceUnitTest.cs
Labels: enhancement

#89 tests run using usersecrets
  .github/workflows/build and test on requests.yml
  src/Chirp.Razor/Program.cs
Labels: refactoring, Testing

#90 refactor from core to infrastructure
  src/Chirp.Core/Chirp.Core.csproj
  src/Chirp.Infrastructure/Chirp.Infrastructure.csproj
  src/Chirp.Infrastructure/Data/ChirpDBContext.cs
  src/Chirp.Infrastructure/Data/DbInitializer.cs
  src/Chirp.Infrastructure/Data/Migrations/20241119075821_InitialDBSchema.Designer.cs
  src/Chirp.Infrastructure/Data/Migrations/20241119075821_InitialDBSchema.cs
  src/Chirp.Infrastructure/Data/Migrations/20241125103220_FollowerDBSchema.Designer.cs
  src/Chirp.Infrastructure/Data/Migrations/20241125103220_FollowerDBSchema.cs
  src/Chirp.Infrastructure/Data/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Repositories/FollowRepository.cs
  src/Chirp.Razor/Chirp.Razor.csproj
  src/Chirp.Razor/Program.cs
  test/Chirp.InfrastructureTest/GlobalUsings.cs
Labels: refactoring

#93 #81, #82 Extra End2End tests
  test/Chirp.RazorTest/End2EndTests/BadActorTests.cs
  test/Chirp.RazorTest/End2EndTests/BadInteractionsTest.cs
  test/Chirp.RazorTest/End2EndTests/BasicUserFeaturesTest.cs
  test/Chirp.RazorTest/PlaywrightPageTester.cs
Labels: Testing

#94 Epic emergency fix of delete cheep test
  test/Chirp.RazorTest/End2EndTests/BasicUserFeaturesTest.cs
Labels: bug

#95 fix editcheep
  src/Chirp.Razor/Pages/Shared/_CheepList.cshtml
Labels: bug

#96 Documentation
  docs/images/Architecture.png
  docs/images/Chirp.drawio.png
  docs/images/DeploymentArchitecture.png
  docs/images/DomainModel.png
  docs/images/UserActivityStatechart.png
  docs/images/bdsaprojectboard.png
  docs/images/bdsaworkflow.png
  docs/images/githubWorkflowUmlActivityDiagrams.png
  docs/report.md
Labels: documentation
